.circleci/config.yml
.rubocop.yml
Gemfile
README.md
influxdb-client.gemspec
influxdb_client.gemspec
lib/influxdb/client.rb
lib/influxdb/client/client.rb
lib/influxdb/client/version.rb
lib/influxdb/client/write_api.rb
lib/influxdb_client.rb
lib/influxdb_client/client.rb
lib/influxdb_client/write_api.rb
test/influx_db_client_test.rb
test/influxdb/client_test.rb
test/test_helper.rb

Class structure

---

.circleci/config.yml
.rubocop.yml
README.md
influxdb-client.gemspec
lib/influxdb/client.rb
lib/influxdb/client/client.rb
lib/influxdb/client/influx_error.rb
lib/influxdb/client/point.rb
lib/influxdb/client/write_api.rb
test/influxdb/client_test.rb
test/influxdb/point_test.rb
test/influxdb/write_api_test.rb
test/test_helper.rb

feat: write api

---

.circleci/config.yml
README.md
lib/influxdb/client/client.rb
lib/influxdb/client/influx_error.rb
lib/influxdb/client/write_api.rb
test/influxdb/write_api_integration_test.rb
test/influxdb/write_api_test.rb

added integration test

---

.circleci/config.yml
bin/influxdb-onboarding.sh

- speed up build
- build over different version of Ruby

Use CircleCI containers instead machine

---

.circleci/config.yml

CircleCI also build over Ruby 2.7
cc @giovannelli (#8)

Add build with Ruby 2.7

---

README.md

chore(readme): update links

---

CHANGELOG.md
README.md
lib/influxdb2/client/flux_csv_parser.rb
lib/influxdb2/client/query_api.rb
test/influxdb/flux_csv_parser_test.rb
test/influxdb/query_api_stream_test.rb

Query stream

---

CHANGELOG.md
README.md
lib/influxdb2/client/client.rb
lib/influxdb2/client/point.rb
lib/influxdb2/client/worker.rb
lib/influxdb2/client/write_api.rb
test/influxdb/write_api_batching_test.rb

Batch write

---

CHANGELOG.md
README.md
lib/influxdb2/client/influx_error.rb
lib/influxdb2/client/worker.rb
lib/influxdb2/client/write_api.rb
test/influxdb/write_api_batching_test.rb
test/influxdb/write_api_test.rb

Add jitter_interval and retry_interval to WriteApi

---

CHANGELOG.md
lib/influxdb2/client/default_api.rb
test/influxdb/delete_api_test.rb
test/influxdb/query_api_test.rb
test/influxdb/write_api_test.rb

feat: add User-Agent request header

---

.rubocop.yml
CHANGELOG.md
lib/influxdb2/client/flux_csv_parser.rb
test/influxdb/flux_csv_parser_test.rb

fix: Correctly parse CSV where multiple results include multiple tables

---

CHANGELOG.md
influxdb-client.gemspec

fix: Upgrade rake to version 12.3.3

---

CHANGELOG.md
README.md
examples/influxdb_18_example.rb

docs: Clarify how to use a client with InfluxDB 1.8

---

.rubocop.yml
CHANGELOG.md
lib/influxdb2/client/default_api.rb
lib/influxdb2/client/delete_api.rb
lib/influxdb2/client/health_api.rb
lib/influxdb2/client/query_api.rb
lib/influxdb2/client/write_api.rb
test/influxdb/client_test.rb
test/influxdb/write_api_test.rb

Releated-to https://github.com/influxdata/influxdb-client-python/issues/87

feat: remove trailing slash from connection URL

---

CHANGELOG.md
bin/swagger.yml
lib/influxdb2/client/models/health_check.rb
lib/influxdb2/client/models/query.rb

feat: Updated swagger to latest version

---

README.md

Fix typo flushInterval -> flush_interval

---

CHANGELOG.md
lib/influxdb2/client/flux_csv_parser.rb
test/influxdb/flux_csv_parser_test.rb

CSV parser is able to parse export from UI

feat: CSV parser is able to parse export from UI

---

.circleci/config.yml
CHANGELOG.md

chore: added Ruby 3.0 to CI

---

.circleci/config.yml
bin/generate-sources.sh

Closes #
Added check info CircleCI to test freshness of generated Management API.

chore: added check to test freshness of generated Management API

---

CHANGELOG.md
apis/lib/influxdb2/apis/generated/models/retention_rule.rb

Updated Swagger API to latest version.

chore: updated Swagger API to latest version

---

README.md
apis/README.md

Added unified documentation section.

docs: add client docs links

---

test/influxdb/client_test.rb

Fix tests to be compatible with InfluxDB 2.2.

fix(test): reflect changes in InfluxDB 2.2

---

.circleci/config.yml
apis/influxdb-client-apis.gemspec
influxdb-client.gemspec

Fix CI build for all supported Ruby version.

fix: tests
