influxdata/influxdb-client-ruby

.gitignore, lib/influxdb/client/write_api.rb
Copied from fork: https://github.com/bednar/influxdb-client-ruby/pull/1
cc @giovannelli
-------
Hi @bednar,
I'm testing influxdb 2.0 but with my cloud endpoint I got this:
```
JSON::ParserError (767: unexpected token at '<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>openresty</center>
</body>
</html>
```
use_ssl option fix the issue, but I'm still not able to write a point! Getting this
```
<Net::HTTPNoContent 204 No Content readbody=true> 
```
Does this ring any bell to you?
Thank you,
Duccio
=> Set http.use_ssl with @options[:use_ssl] default false

CHANGELOG.md, lib/influxdb2/client/flux_csv_parser.rb, lib/influxdb2/client/worker.rb, test/influxdb/write_api_batching_test.rb
=> fix: batch write

CHANGELOG.md, lib/influxdb2/client/default_api.rb, lib/influxdb2/client/delete_api.rb, lib/influxdb2/client/query_api.rb, lib/influxdb2/client/write_api.rb, test/influxdb/delete_api_test.rb, test/influxdb/query_api_test.rb, test/influxdb/write_api_test.rb
We recently started requiring `Content-Type` headers in InfluxDB 2.x API. This ensures the client is sending the appropriate headers.
=> fix(influxdb2/client): Send Content-Type headers

CHANGELOG.md, lib/influxdb2/client/point.rb, test/influxdb/point_test.rb
Related to https://github.com/influxdata/influxdb-client-java/issues/127
* serialization of `\n`, `\r` and `\t` to Line Protocol
* `=` is valid sign for measurement name
=> fix: serialization of `\n`, `\r` and `\t` to Line Protocol,  `=` is valid sign for measurement name 

CHANGELOG.md, lib/influxdb2/client/worker.rb
Closes #43 
Removes `.positive?` method, which is not supported in Ruby 2.2, in favor of basic comparison to zero.
EDIT: noticing that spec coverage is only for Ruby 2.4 and up, but gemspec supports >= Ruby 2.2.
=> fix: Remove `positive?` breaking in Ruby 2.2

.rubocop.yml, CHANGELOG.md, README.md, lib/influxdb2/client/default_api.rb, lib/influxdb2/client/influx_error.rb, lib/influxdb2/client/worker.rb, lib/influxdb2/client/write_api.rb, test/influxdb/write_api_batching_test.rb
=> feat: Add max_retries, max_retry_delay and exponential_base to WriteApi

.circleci/config.yml, CHANGELOG.md, README.md, bin/influxdb-onboarding.sh, bin/influxdb-restart.sh, lib/influxdb2/client/client.rb, test/influxdb/client_test.rb, test/influxdb/delete_api_integration_test.rb, test/influxdb/delete_api_test.rb, test/influxdb/query_api_integration_test.rb, test/influxdb/query_api_stream_test.rb, test/influxdb/query_api_test.rb, test/influxdb/write_api_batching_test.rb, test/influxdb/write_api_integration_test.rb, test/influxdb/write_api_test.rb
Closes #49
- default port changed to 8086
=> chore: default port changed to 8086

CHANGELOG.md, lib/influxdb2/client/worker.rb
Closes #51 
- avoid to abort all threads
=> fix: abort only worker threads

CHANGELOG.md, README.md, lib/influxdb2/client/worker.rb, lib/influxdb2/client/write_api.rb, test/influxdb/write_api_batching_test.rb
Related-to #51
- `abort_on_exception`  on `worker` is configurable
- default strategy is **best-effort** - after fail, continue with next batch
=> feat: default strategy for batching worker is best-effort

.rubocop.yml, CHANGELOG.md, lib/influxdb2/client/client.rb, lib/influxdb2/client/default_api.rb, lib/influxdb2/client/worker.rb, test/influxdb/default_api_test.rb, test/influxdb/write_api_batching_test.rb, test/test_helper.rb
The message looks like:
_The retriable error occurred during writing of data. Reason: 'org 04014de4ed590000 has exceeded limited_write plan limit'. Retry in 5s._
=> feat: improved logging message for retries

CHANGELOG.md, README.md, lib/influxdb2/client/flux_csv_parser.rb, test/influxdb/flux_csv_parser_test.rb, test/influxdb/query_api_integration_test.rb, test/influxdb/query_api_test.rb
Closes #60
The query parser uses nanosecond precision for dates. - e.g. `1970-01-01T00:00:00.000123456+00:00`
=> fix: query results has precision with nanosecond

CHANGELOG.md, README.md, lib/influxdb2/client/client.rb, lib/influxdb2/client/default_api.rb, test/influxdb/default_api_test.rb
Related to https://github.com/influxdata/influxdb-plugin-fluent/issues/22
Added the new option to customise certification verification behaviour:
| Option | Description | Type | Default |
|---|---|---|---|
| verify_mode | Sets the flags for the certification verification at beginning of SSL/TLS session. | `OpenSSL::SSL::VERIFY_NONE` or `OpenSSL::SSL::VERIFY_PEER` | none |
=> feat: add possibility to specify the certification verification behaviour

CHANGELOG.md, apis/LICENSE, apis/influxdb-client-apis.gemspec, lib/influxdb2/client/version.rb
Avoid uses sources from parent path:
```
Gem::Package::PathError: installing into parent path /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/CHANGELOG.md of /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/influxdb-client-apis-1.12.0 is not allowed
```
=> fix: avoid uses sources from parent path

.codecov.yml, CHANGELOG.md, apis/lib/influxdb2/apis/generated/api/authorizations_api.rb
Updated Swagger API to latest version.
=> chore: update Swagger API to latest version

.circleci/config.yml, CHANGELOG.md
Closes #72
Add build configuration for `jruby`.
=> chore(ci): add build configuration for jruby

CHANGELOG.md, lib/influxdb2/client/flux_csv_parser.rb, test/influxdb/flux_csv_parser_test.rb
Related to https://github.com/influxdata/influxdb-client-java/issues/239
Fixed parsing `Inf+` for [histogram() function](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/histogram/).
```csv
#group,false,false,true,true,true,true,true,true,true,true,false,false
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,string,string,string,string,string,string,double,double
#default,_result,,,,,,,,,,,
,result,table,_start,_stop,_field,_measurement,language,license,name,owner,le,_value
,,0,2021-06-23T06:50:11.897825012Z,2021-06-25T06:50:11.897825012Z,stars,github_repository,C#,MIT License,influxdb-client-csharp,influxdata,0,0
,,0,2021-06-23T06:50:11.897825012Z,2021-06-25T06:50:11.897825012Z,stars,github_repository,C#,MIT …
```
=> fix: parsing infinite numbers

CHANGELOG.md, README.md, lib/influxdb2/client/client.rb, lib/influxdb2/client/default_api.rb, lib/influxdb2/client/version.rb, test/influxdb/redirect_test.rb, test/influxdb/write_api_test.rb
1. `Authorization` header is not forwarded when redirect leads to a different domain
2. Fix redirect location
3. Add documentation how to configure proxy
=> feat: `Authorization` header is not forwarded when redirect leads to a different domain

CHANGELOG.md, lib/influxdb2/client/influx_error.rb, test/influxdb/write_api_batching_test.rb, test/influxdb/write_api_test.rb
This PR fixes handling of plain-text http errors.
=> fix: parse 503 plain text error

.circleci/config.yml
Fixed nightly build:
- https://github.com/rubygems/rubygems/pull/2596
- https://github.com/rubygems/rubygems/pull/3983
=> fix(ci): use proper way how to build a gem from other directory

.circleci/config.yml, .gitignore, CHANGELOG.md, apis/lib/influxdb2/apis/generated/models/resource.rb, bin/generate-sources.sh, bin/pom.xml
Added missing `PermissionResource` types.
=> fix: add missing PermissionResource types from Cloud definition

.circleci/config.yml, CHANGELOG.md
=> chore(ci): add Ruby 3.1 to CI build

CHANGELOG.md, examples/README.md, examples/record_row_example.rb, influxdb-client.gemspec, lib/influxdb2/client/flux_csv_parser.rb, lib/influxdb2/client/flux_table.rb, test/influxdb/flux_csv_parser_test.rb
Adding possibility of accessing response data in Array FluxRecord.row.
In case of using pivot on data, where field contains labels that occur by default in the annotated CSV (f.e. "result" or "table"), could be duplicated column names in response. In that case FluxRecord.values (Hash), which can hold only unique keys, doesn't show complete data. This edge case is solved by using FluxRecord.row (Array).
=> feat: add FluxRecord.row with response data stored in Array

CHANGELOG.md, lib/influxdb2/client/flux_csv_parser.rb, test/influxdb/query_api_test.rb
Closes #122
Fixed return types for `query` method.
=> fix: `query` return type is `Array`

.rubocop-cops.yml, CHANGELOG.md, README.md, examples/create_new_bucket.rb, examples/influxdb_18_example.rb, examples/invokable_scripts.rb, examples/parameterized_query.rb, examples/record_row_example.rb, lib/influxdb2/client/client.rb, test/influxdb/client_test.rb
Closes #120
The **InfluxDB::Client** can be also used as a resource:
```ruby
InfluxDB2::Client.use('https://localhost:8086', 'my-token') do |client|
client.do_something
end
```
=> feat: client can be used as a resource

CHANGELOG.md, lib/influxdb2/client/point.rb, lib/influxdb2/client/version.rb, test/influxdb/point_test.rb
_Briefly describe your proposed changes:_ Timestamps present in fields and tags are not converted into integers. They should be converted. This PR handles that and converts timestamps from tags and fields into integers. This change is required for [influxdb-rails 2.0](https://github.com/influxdata/influxdb-rails).
=> fix: escape timestamps for fields and tags

CHANGELOG.md, lib/influxdb2/client/influx_error.rb
An influxdb v1.8 HTTP error response message was not correctly transferred to ruby InfluxError message. Hence, in case of an InfuxDB v1.8 Error response, the reason (except status code) was not traceable.
Closes #133
After parsing the response body of an InfuxDB Error response, the information of it is wrapped into an `InfluxDB2::InfluxError`.
Evaluation of the error message has to be different for InfluxDB v1.8 and InfuxDB v2.x, because the response body is different.
How the fix works:
- InfluxDB v2.x uses the `message` key for this
- InfluxDB v1.8 uses the `error` key for this
-> previously only `message` was supported
-> now, in case `message` is blank, `error` is checked
=> fix: support influxdb v1.8 HTTP error response message

CHANGELOG.md, influxdb-client.gemspec
Closes #136
Add the csv gem to the gemspec dependencies.
=> chore(deps): add csv dependency as required by ruby 3.3
